# utils/name_normalizer.py
#
# Mapea variantes en español (y errores comunes) al nombre exacto
# que devuelve la API. Las claves están en minúsculas para hacer
# la búsqueda case-insensitive.

TEAM_NAME_MAP: dict[str, str] = {

    # ── América del Sur ───────────────────────────────────────────
    "argentina": "Argentina",
    "brasil": "Brazil",
    "brazil": "Brazil",
    "uruguay": "Uruguay",
    "colombia": "Colombia",
    "ecuador": "Ecuador",
    "venezuela": "Venezuela",
    "paraguay": "Paraguay",
    "bolivia": "Bolivia",
    "chile": "Chile",
    "peru": "Peru",
    "perú": "Peru",

    # ── América del Norte y Central ───────────────────────────────
    "mexico": "Mexico",
    "méxico": "Mexico",
    "estados unidos": "USA",
    "usa": "USA",
    "united states": "USA",
    "eeuu": "USA",
    "ee.uu.": "USA",
    "canada": "Canada",
    "canadá": "Canada",
    "honduras": "Honduras",
    "panama": "Panama",
    "panamá": "Panama",
    "costa rica": "Costa Rica",
    "jamaica": "Jamaica",

    # ── Europa ────────────────────────────────────────────────────
    "francia": "France",
    "france": "France",
    "inglaterra": "England",
    "england": "England",
    "españa": "Spain",
    "spain": "Spain",
    "alemania": "Germany",
    "germany": "Germany",
    "italia": "Italy",
    "italy": "Italy",
    "portugal": "Portugal",
    "holanda": "Netherlands",
    "países bajos": "Netherlands",
    "paises bajos": "Netherlands",
    "netherlands": "Netherlands",
    "bélgica": "Belgium",
    "belgica": "Belgium",
    "belgium": "Belgium",
    "croacia": "Croatia",
    "croatia": "Croatia",
    "serbia": "Serbia",
    "suiza": "Switzerland",
    "switzerland": "Switzerland",
    "dinamarca": "Denmark",
    "denmark": "Denmark",
    "polonia": "Poland",
    "poland": "Poland",
    "austria": "Austria",
    "turquia": "Turkey",
    "turquía": "Turkey",
    "turkey": "Turkey",
    "suecia": "Sweden",
    "sweden": "Sweden",
    "noruega": "Norway",
    "norway": "Norway",
    "eslovaquia": "Slovakia",
    "slovakia": "Slovakia",
    "eslovenia": "Slovenia",
    "slovenia": "Slovenia",
    "republica checa": "Czechia",
    "república checa": "Czechia",
    "chequia": "Czechia",
    "czechia": "Czechia",
    "czech republic": "Czechia",
    "grecia": "Greece",
    "greece": "Greece",
    "bosnia": "Bosnia-Herzegovina",
    "bosnia herzegovina": "Bosnia-Herzegovina",
    "bosnia y herzegovina": "Bosnia-Herzegovina",
    "bosnia-herzegovina": "Bosnia-Herzegovina",
    "bosnia and herzegovina": "Bosnia-Herzegovina",
    "ucrania": "Ukraine",
    "ukraine": "Ukraine",
    "escocia": "Scotland",
    "scotland": "Scotland",
    "gales": "Wales",
    "wales": "Wales",
    "hungria": "Hungary",
    "hungría": "Hungary",
    "hungary": "Hungary",
    "rumania": "Romania",
    "rumanía": "Romania",
    "romania": "Romania",
    "albania": "Albania",
    "georgia": "Georgia",

    # ── África ────────────────────────────────────────────────────
    "marruecos": "Morocco",
    "morocco": "Morocco",
    "senegal": "Senegal",
    "camerun": "Cameroon",
    "camerún": "Cameroon",
    "cameroon": "Cameroon",
    "ghana": "Ghana",
    "nigeria": "Nigeria",
    "costa de marfil": "Ivory Coast",
    "côte d'ivoire": "Ivory Coast",
    "cote d'ivoire": "Ivory Coast",
    "ivory coast": "Ivory Coast",
    "egipto": "Egypt",
    "egypt": "Egypt",
    "tunez": "Tunisia",
    "túnez": "Tunisia",
    "tunisia": "Tunisia",
    "argelia": "Algeria",
    "algeria": "Algeria",
    "sudafrica": "South Africa",
    "sudáfrica": "South Africa",
    "south africa": "South Africa",
    "congo": "DR Congo",
    "rd congo": "DR Congo",
    "republica democratica del congo": "DR Congo",
    "república democrática del congo": "DR Congo",
    "dr congo": "DR Congo",
    "congo dr": "DR Congo",
    "mali": "Mali",
    "malí": "Mali",
    "burkina faso": "Burkina Faso",
    "cabo verde": "Cape Verde",
    "cape verde": "Cape Verde",
    "tanzania": "Tanzania",
    "uganda": "Uganda",
    "zimbabue": "Zimbabwe",
    "zimbabwe": "Zimbabwe",

    # ── Asia y Oceanía ────────────────────────────────────────────
    "japon": "Japan",
    "japón": "Japan",
    "japan": "Japan",
    "corea del sur": "Korea Republic",
    "corea": "Korea Republic",
    "korea republic": "Korea Republic",
    "south korea": "Korea Republic",
    "arabia saudita": "Saudi Arabia",
    "arabia saudí": "Saudi Arabia",
    "saudi arabia": "Saudi Arabia",
    "iran": "IR Iran",
    "irán": "IR Iran",
    "ir iran": "IR Iran",
    "qatar": "Qatar",
    "catar": "Qatar",
    "irak": "Iraq",
    "iraq": "Iraq",
    "australia": "Australia",
    "china": "China",
    "uzbekistan": "Uzbekistan",
    "uzbekistán": "Uzbekistan",
    "jordania": "Jordan",
    "jordan": "Jordan",
    "indonesia": "Indonesia",
    "nueva zelanda": "New Zealand",
    "nueva zelandia": "New Zealand",
    "new zealand": "New Zealand",
    "oman": "Oman",
    "omán": "Oman",
    "barein": "Bahrain",
    "baréin": "Bahrain",
    "bahrain": "Bahrain",
    "emiratos arabes unidos": "UAE",
    "emiratos árabes unidos": "UAE",
    "uae": "UAE",
    "united arab emirates": "UAE",
}


def normalize_team_name(name: str) -> str:
    """
    Recibe el nombre tal como lo escribió el usuario y devuelve
    el nombre exacto que usa la API. Si no encuentra coincidencia,
    devuelve el input original (para que el mensaje de error
    en el comando muestre lo que escribió el usuario).

    Ejemplo:
        normalize_team_name("república checa") → "Czechia"
        normalize_team_name("Japón")           → "Japan"
        normalize_team_name("France")          → "France"
    """
    if not name:
        return name
    return TEAM_NAME_MAP.get(name.strip().lower(), name.strip())